### ISSUE TITLE
Deploy staging instance

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#1]
Deploy a complete staging instance of the data portal.

##  Acceptance

- [x] Staging site on public URL

## Tasks

* Lots of them ...

**Comment by starsinmypockets** [comment]
See https://gitlab.com/viderum/cloud-honduras-staging for boilerplate

**Comment by aferrarini** [comment]
Hi @pwalsh , 
Could we have an update on this issue ? Thanks !

**Comment by rufuspollock** [comment]
@aferrarini hi, it's all moving along well.

**Comment by rufuspollock** [comment]
This is working.
