### ISSUE TITLE
Investigate dashboard.js [WIP]

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-montreal#11]
Check what needs to be done on dashboard js to expose editor controls, hook into datasets on ckan, and display beautiful charts from any dataset chosen in a given ckan instance/

## Acceptance

- [x] Report on experiment

## Tasks

- [x] Research data
- [x] Research dashboard options
- [x] Trial

**Comment by rufuspollock** [comment]
FIXED.
